apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-gmsk3-run
spec:
  workspaces:
    - name: pipeline-ws
      persistentVolumeClaim:
        claimName: example-local-claim
    - name: dockerconfig
      secret:
        secretName: my-secret
  pipelineRef:
    name: workspace-pipeline6-ref
